name: Development Binaries

on:
  push:
    branches:
      - dev/1.5.x

jobs:
  bianries:
    uses: ./.github/workflows/binaries-build.yaml
    with:
      release: development-binaries
    secrets: inherit
